defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
hydra:
  run:
    dir: runs/predict/resnet/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null 

model:
  name: AudioResnet50
  num_classes: 2 # lamantin or pas_lamantin
  checkpoint_path: "runs/resnet/checkpoints/best.ckpt"
  pre_trained : True
  

data:
  
  pred_dir : data/test_set/extraits_1min
  classes : ['pas_lamantin', 'lamantin']
  batch_size: 32   #######
  num_workers: 4
  sample_rate: 44100    #######
  window: 10    #######
  hop_size: 5    
  img_size : [224, 224]


trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  logger: false
  enable_checkpointing: false
  enable_model_summary: false

seed: 111